apiVersion: apps/v1
kind: Deployment
metadata:
  name: pico-web-server-deployment
spec:
  strategy:
    type: RollingUpdate
  replicas: 3
  selector:
    matchLabels:
      app: pico-web-server-pod
  template:
    metadata:
      name: pico-web-server-pod
      labels:
        environment: production
        app: pico-web-server-pod
    spec:
      containers:
      - name: pico-web-server-prod
        image: syndamia/pico-web-server:latest
        args: [ 'demo,/usr/share/demo,page.md' ]
        ports:
        - containerPort: 8080
        volumeMounts:
        - name: demo-ps
          mountPath: /usr/share/demo
      volumes:
      - name: demo-ps
        persistentVolumeClaim:
          claimName: demo-pvc
