name: Create and release development container
on:
  workflow_run:
    workflows: ["Build, test, security"]
    types:
      - completed
    branches:
      - dev
jobs:
  Create-and-release-dev-container:
    name: Build the dev docker container image and push it to dockerhub
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dawidd6/action-download-artifact@v6
        with:
          github_token: ${{ secrets.TOKEN_GITHUB }}
          run_id: ${{ github.event.workflow_run.id }}
          name: dev-build-files
          path: ./build
      - uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - uses: docker/build-push-action@v5
        with:
          push: true
          context: .
          file: ./docker/dev/Dockerfile
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/pico-web-dev:latest
