name: Check if pr to main is from dev
on:
  pull_request_target:
    branches:
      - 'main'

jobs:
  pr_to_main_from_dev:
    if: github.head_ref != 'dev'
    runs-on: ubuntu-latest
    steps:
    - uses: superbrothers/close-pull-request@v3
      with:
        comment: 'The only allowed pull requests to main are those from dev!'
