name: Create release and push production server image to dockerhub
on:
  push:
    branches:
      - main
jobs:
  Build-docker-and-push:
    name: Build the docker container image and push it to dockerhub
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - uses: docker/build-push-action@v5
        with:
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/pico-web-server:latest

  Release:
    name: Make github release
    runs-on: ubuntu-latest
    needs: Build-docker-and-push
    steps:
      - uses: actions/checkout@v4
      - uses: rymndhng/release-on-push-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN_GITHUB }}
        with:
          bump_version_scheme: minor
