name: Check if pr to main is from dev
on:
  pull_request_target:
    branches:
      - 'main'
jobs:
  pr_to_main_from_dev:
    if: github.head_ref != 'dev'
    permissions:
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
    # - name: Add comment
    #         uses: peter-evans/create-or-update-comment@v4
    #         with:
      - name: Change base to dev
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: gh pr edit --base 'dev'
